### ISSUE TITLE
include promises.jar into core distribution

### ISSUE THREAD

**Issue by MikOfClassX** [akuhtz/timingframework#3]
Hi!

it would be useful to have promises.jar included into the timingframework-core jar assembly.

I tried (unsuccessfully) to mod the mvn build. It seems i'm not that expert..

Cheers!

**Comment by akuhtz** [comment]
Hello,

Not sure what you did. If you checkout the project and run ```mvn install``` it should build without issues. All dependencies are downloaded from central maven repo.

Cheers!

**Comment by MikOfClassX** [comment]
Hi! yep, i am able to build the repo, but the dependency promises-5.6.0.jar is not part of the final timingframework-core-7.4.2-SNAPSHOT.jar as stated here -> https://github.com/akuhtz/timingframework/blob/3487fe0c36c73471f9ad1ea870d39433f6d886f2/timingframework-core/lib/NOTES.txt#L304

**Comment by akuhtz** [comment]
Hello,
Oh, never looked at this file. I think it would be better to remove all these promise annotations as the are no longer actively maintained.

**Comment by MikOfClassX** [comment]
well, that's definitely a good idea :) Any plan ?

**Comment by akuhtz** [comment]
Release 4.7.2 is available at maven central.
